#%RAML 1.0 Trait
headers:
  client_id:
    type: string
    required: true
    example: "83a8df22c2b3435f1f9f09c9"
  client_secret:
    type: string
    required: true
    example: "A744e36efAdF6B963432C9BC"