#%RAML 1.0 Trait
responses:
  400:
    body:
      application/json:
        example: !include ../examples/errorResponseExample/400.json
  401:
    body:
      application/json:
        example: !include ../examples/errorResponseExample/401.json
  404:
    body:
      application/json:
        example: !include ../examples/errorResponseExample/404.json
  405:
    body:
      application/json:
        example: !include ../examples/errorResponseExample/405.json
  406:
    body:
      application/json:
        example: !include ../examples/errorResponseExample/406.json
  415:
    body:
      application/json:
        example: !include ../examples/errorResponseExample/415.json
  500:
    body:
      application/json:
        example: !include ../examples/errorResponseExample/500.json
  501:
    body:
      application/json:
        example: !include ../examples/errorResponseExample/501.json